[package]
name = "vsss-wasm"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]

wit-bindgen-rt = { version = "0.39.0", features = ["bitflags"] }
#vsss-rs = { git = "https://github.com/zorvan/vsss-rs.git", features = ["curve25519", "alloc"]}
vsss-rs = { version = "5.3.0", features = ["curve25519", "alloc", "serde"] }

elliptic-curve = { version = "0.13", features = ["ecdh"] }
curve25519-dalek = { version = "4" }
typenum = "1.17"

rand = "0.8.5"
rand_chacha = "0.3.1"
getrandom = { version = "0.2.15", features = ["js"]}

serde = { version = "1.0", features = ["derive"] }
serde_bare = "0.5"

sha2 = "0.10"
chacha20poly1305 = "0.10"

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true

[package.metadata]
wasm-opt = true
wasm-name-section = true
wasm-producers-section = true

[package.metadata.component]
package = "component:vsssworld"

[package.metadata.component.dependencies]
